ipfs/js-ipfsd-ctl

.gitignore, README.md, examples/id.js, examples/local.js, index.js, package.json, test/test.js
I would like it to actually do init automatically as well, then i'll update the readme.
=> First draft

index.js, package.json
This makes the path valid regardless of whether 'ipfs-api' is a child module of this module, or of one of this module's parents.
Resolves #13.
=> Determines the IPFS binary path dynamically.

package.json
Maybe there is a reason you are not using semver ranges on the dependencies, but this patch fixes that!  Feel free to reject if this isn't wanted.
=> Update package.json to use semver ranges

index.js, package.json
This library properly exits the process on errors and does not
interfere on `require`.
Ref https://github.com/ipfs/js-ipfs-api/issues/88
Fixes #19
=> fix: Switch shutdown handler library 

package.json
We should bump the minor version when realising this.
=> feat: Upgrade deps, including ipfs to 0.3.11

index.js, lib/node.js, test/test.js
process.cwd() in Electron will always return '/' instead of the current directory (https://github.com/electron/electron/issues/2108). By checking if we're using Electron, we can get Electron app's default folder instead of '/'.
```javascript
const rootPath = process.versions['electron'] ? process.resourcesPath + '/app/' : process.cwd()
const ipfsDefaultPath = path.join(rootPath, 'node_modules/go-ipfs-dep/go-ipfs/ipfs')
```
This PR adds that check and tests to cover the Electron vs Node.js use cases.
=> Fix default IPFS exec path when used via Electron

lib/node.js, package.json, test/test.js
this pr will fix the problem of ipfsd-ctl not working with npm2. in addition the electron path check is not needed anymore because of the use of __dirname in rootPath.
=> add check for npm2 path and remove electron path check

package.json, src/node.js, test/index.spec.js
d74045f (jbenet, 2 minutes ago)
feat(startDeamon): allow passing flags to ipfs daemon
9c4dbce (jbenet, 4 minutes ago)
fix(startDaemon): fix the behavior of startDeamon
- now waits for "Daemon is ready"
- also tracks Gateway address
- checks failures on startup, and returns an error if so
- this was a serious bug-- would not detect errors.
- fails correctly, without leaving the process hanging
b523b1c (jbenet, 7 minutes ago)
fix: rm unused var (thanks, linter)
efa2aa4 (jbenet, 10 minutes ago)
note(shutdown): comment on problematic func name
d6ad480 (jbenet, 14 minutes ago)
fix(shutdown): fixed bugs in stopDaemon
- bug1: local var for the closure (this.subprocess set to null)
- bug2: order problem: should set .on('close') handler before .kill()
3c50894 (jbenet, 17 minutes ago)
fix(tests): …
=> bugfixes and improvements (ipfs daemon flags)

package.json
related to https://github.com/diasdavid/go-ipfs-dep/pull/9
this should allow me to debug ipfs-log on windows.
cc @haadcode @dignifiedquire
=> update go-ipfs-dep to v0.4.3-2

src/node.js
In the case that no config file exists, the error generated by `fs.readFileSync` is uncaught.  This results in the `done` callback not being called.
=> Fail gracefully when config file is not found

src/index.js, test/index.spec.js
This PR will change the local() api so that options object can be passed to it.
PRing this again (original https://github.com/ipfs/js-ipfsd-ctl/pull/109).
=> feat(init): Add the possibility to pass options to init()

.gitignore, .travis.yml, README.md, example.js, package.json, src/exec.js, src/index.js, src/node.js, test/exec.spec.js, test/index.spec.js, test/run.spec.js, test/survivor
- upgrade aegir
- upgrade dependencies
- handle stream errors when setting the config
- use pump instead of pipe
I've also pulled in the changes from subcomandante to execa from #89
=> feat: better stream handling

package.json, src/exec.js, src/node.js, test/exec.spec.js
The bug reported by https://github.com/ipfs/js-ipfsd-ctl/issues/143 was introduced with https://github.com/ipfs/js-ipfsd-ctl/commit/a0adc8225164e4edfbe9346cc93c50c3f6bd71c2, I'm still super intrigued how the tests passed the scripts pre-release, but truth is that I'm not being able to get to pass now.
Found a issue with the `psExpect` function where the grace countdown had to be `--grace`, otherwise it would never reach 0.
The test failing is that SIGKILL is not effectively killing the process, however the test here is straight out copy of https://github.com/jbenet/node-subcomandante/blob/master/test/test.js#L73-L97 and I've been tinkering back and forward, making both match and I can't seem to figure out exactly where the issue is coming from.
Going to visit this back tomorrow, otherwise …
=> Lingering daemons

src/node.js, test/index.spec.js
This PR will add a properties to get the address the gateway was started at and can be accessed with:
```javascript
ipfs.gatewayHost
ipfs.gatewayPort
```
=> Add gateway address to the returned IPFS api

test/index.spec.js
This should fix https://github.com/ipfs/js-ipfsd-ctl/issues/156
This still does **NOT** fix the "occasional" random CI errors 
```
1) daemons startDaemon starts the daemon and returns valid API and gateway addresses:
Uncaught AssertionError: expected null to be an instance of Multiaddr
```
as seen here https://travis-ci.org/ipfs/js-ipfsd-ctl/builds/245233174 
or here https://travis-ci.org/ipfs/js-ipfsd-ctl/builds/244451297
=> tests improves tmp dir

.appveyor.yml, README.md, examples/disposableApi.js, examples/electron-asar/.gitignore, examples/electron-asar/app.js, examples/electron-asar/package.json, examples/electron-asar/public/index.html, examples/electron-asar/readme.md, examples/id.js, examples/local.js, src/exec.js, src/node.js, test/index.spec.js
js-ipfsd-ctl will not work inside an asar container, see https://github.com/ipfs/js-ipfsd-ctl/issues/94.
A possible solution is to exclude the ipfs binary from asar, with the unpackDir option
```bash
electron-packager ./ --asar.unpackDir=node_modules/go-ipfs-dep
```
(EDITED: changed `go-ipfs-dep/**` to `go-ipfs-dep` ) 
on MacOS: this will package everything expect go-ipfs-dep into `<appname>.asar`
and put go-ipfs-dep into `<appname>.asar.unpacked/node_modules/go-ipfs-dep`
This change request adds a check if `.asar/` is part of the path and changes it to `.asar.unpacked/`
Edit:
Assuming you have a project using ipfsd-ctl, electron and electron-packager. 
Install https://github.com/thisconnect/js-ipfsd-ctl/tree/asar-unpacked
```
npm i thisconnect/js-ipfsd-ctl#asar-unpacked
```
build …
=> replaces path to .asar.unpacked if cmd includes .asar/node_modules

package.json, src/daemon.js, src/index.js, test/index.spec.js, test/npm-installs.spec.js, test/spawning-daemons.spec.js
It seems that **running our tests in Node.js 8 always fail in AppVeyor and locally** (not in Travis or Circle CI interestingly enough)
=> Slay the Dragon!

.appveyor.yml, src/daemon.js, test/npm-installs.spec.js
Background discussion on https://github.com/ipfs/js-ipfs-api/issues/623
=> Windows interop

package.json, test/spawning-daemons.spec.js
=> Enable skipped windows tests

src/daemon.js
This fixes a small bug where you couldn't init a repository in a different directory than HOME because `this.env` wasn't being updated. I decided to make it a getter so you wouldn't need to change it every time you changed the path.
=> fix: init on different path

src/in-proc-node.js, src/utils/index.js
- Passphrase for in-proc node #186
- Running JS on Windows #185
=> Various enhancements

README.md, src/daemon-node.js, src/in-proc-node.js
=> add passphrase to init options

src/utils/run.js
When running a script that involves `ipfsd-ctl` and you pass on
additional parameters it used to pass on those parameters to
the subprocesses it spaws. This lead to issues especially with
`--inspect-brk` as it would spawn another inspector which then
would fail because there is already one running on the same port.
Fixes #202.
=> fix: don't pass on arguments from node executable

README.md, src/endpoint/server.js, src/factory-client.js
Given that a solution is only being applied temporarily here https://github.com/ipfs/js-ipfs/pull/1103/files#r169972169 by @VictorBjelkholm, let's at least have the tests passing with flying colors and create a proper solution in aegir itself, tracked https://github.com/ipfs/aegir/issues/201
=> fix: try with a different port

src/ipfsd-daemon.js
The keysize was not being passed on the command line. 
`args.concat` does not modify the arrays, it creates a new array.
=> keysize is being ignored

src/ipfsd-daemon.js
If environment variables are passed it, they weren't actually passed
on as `env` haven't had a setter.
=> fix: pass on environment variables

src/endpoint/routes.js, src/factory-client.js, src/factory-in-proc.js, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, test/spawn-options.spec.js
While working on some go/js interop tests I noticed that a daemon spawned on an already-initialized repo doesn't report itself as initialized.
It turned out to be just a typo so I fixed that and added a test.
**Update**
This PR has four fixes related to `proc` node startup:
- `proc` nodes error when reporting their version: [here](https://github.com/ipfs/js-ipfsd-ctl/pull/212/files#diff-5518d51550f18454b1bdcfed570fbbbcR71)
- `proc` nodes spawn before their IPFS instance has finished booting: [here](https://github.com/ipfs/js-ipfsd-ctl/pull/212/files#diff-5518d51550f18454b1bdcfed570fbbbcR138)
- `proc` nodes do not report themselves as initialized: [here](https://github.com/ipfs/js-ipfsd-ctl/pull/212/files#diff-5518d51550f18454b1bdcfed570fbbbcR139)
- daemons spawned remotely do not report …
=> fix: daemon should recognize previously created repos.

.gitignore, src/factory-in-proc.js, src/ipfsd-in-proc.js
When using node event emitter error events should always be handled and propagated, i'm doing a fix on ipfs cli related to this issue https://github.com/ipfs/js-ipfs/issues/1180 and couldn't catch errors coming from ipfsd this PR fixes that.
=> fix: error event propagation

package.json
I `npm link`'d to ipfs@master and the tests passed
=> chore: upgrade ipfs-api to v21

src/utils/find-ipfs-executable.js, test/utils.spec.js
If we use `require.resolve` to find the ipfs executable, we don't have to assume anything about the file system (e.g. that a `node_modules` folder exists).  This is useful if you're running a mono-repo and your dependencies have been hoisted, for example.
=> chore: use require.resolve to find ipfs

test/exec.node.js, test/survivor
There was a suite of tests that were being bypassed during CI with the assumption that the CI environment was buggy.  Turns out it was the tests.  They were failing locally for me too.
It was not using the dirty-chai so the expect.to.not.exist was failing.
It was also trying to trap SIG* with bin/sh which does not recognize those signals (dropping the SIG prefix works in sh)
This SIG* trapping was what I think was making CI tests fail so I enabled testing in CI again.
I waited to make this PR till jenkins had run the tests and these ones are now passing (I know others aren't and there is another issue to address those)
=> chore:test fix exec.node.js tests

README.md, src/endpoint/routes.js, src/ipfsd-client.js, src/ipfsd-daemon.js, test/endpoint/client.js, test/endpoint/routes.js, test/start-stop.node.js
Adding a timeout param to `stop` and `killProcess` as well as increasing the default grace timeout for non disposable nodes proposed in https://github.com/ipfs/js-ipfsd-ctl/issues/226#issuecomment-379041502.
> - disposable repos do what they do now when calling stop
> - non disposable repos have a longer timeout by default
> - modify ipfsd.stop to allo passing a timeout that allows the user controlling the behavior
~~_note: don't merge, tests still need work_~~
_this is ready for review_
=> feat: add timeout to stop and killProcess

src/ipfsd-daemon.js, src/utils/exec.js, test/api.spec.js, test/exec.node.js, test/fixtures/error.js, test/fixtures/talky.js, test/start-stop.node.js
* Renames handlers to stderr and stdout to better reflect what they do.
* Hooks up stderr handler to data event of daemon's stderr to log data emitted.
* Uses the callback to handle process errors instead of an extra error handler.
* Specify stderr and stdout handlers in the method options instead of in a separate argument.
* No longer buffers all command output automatically as it can lead to out of memory errors on long running processes, instead the calling code can choose to receive stdout/stderr or not.
* Does not treat any data emitted on stderr as a reason to judge a process as failed when no stderr handler is passed
=> feat: log stderr from daemon

src/ipfsd-in-proc.js, test/spawn-options.spec.js
`config` was not being passed to the IPFS instance when using the proc daemon. This would make it difficult to prevent an in process js daemon from automatically bootstrapping to discovery servers (the default IPFS behavior).
I am currently using this to test the private network addition to js-ipfs and want to avoid auto connecting to public networks.
=> fix: pass config to ipfs for proc daemon

README.md, src/factory-client.js, src/factory-daemon.js, src/factory-in-proc.js, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, src/utils/repo/browser.js, src/utils/repo/nodejs.js, test/custom-api.spec.js
We decided in https://github.com/ipfs/js-ipfsd-ctl/pull/257 that it would be best to bundle ipfs, ipfs-api and go-ipfs-dep but allow the user to pass their own implementations for "advanced mode" usage aka. us and our tests.
This PR is step 1 and it allows the user to pass an `IpfsApi` constructor to `Factory.create` or `f.spawn`.
=> feat: allows a custom IpfsApi constructor to be used

src/ipfsd-in-proc.js
For implementing the tests for `IPNS over Pubsub` on `js-ipfs` using a `type: proc` daemon, we need to have the `--enable-namesys-pubsub` option properly handled. 
Moreover, I cannot add a test for it, similar to the one already available for `--enable-pubsub-experiment`, as it is not available in the last released version of `js-ipfs`. Once this is merged, I will create an Issue for adding those tests and when `IPNS over Pubsub` PR is merged and released, I will get back here for adding the proper test.
=> fix: add namesys pubsub option

src/ipfsd-daemon.js
"API is listening..." changed to "API listening..." and no longer matches the regex.
N.B. is backwards compatible with older versions of the daemon.
Required for https://github.com/ipfs/js-ipfs/pull/1595
=> fix: CLI scraping of API and Gateway addresses

package.json, src/utils/exec.js, test/exec.node.js
This PR swaps subcomandante for execa to execute daemon cmds, `execa` is widely used by the js community, stable, well maintained by a well known js dev, nicer to work with, faster (check benchmarks below).
This will also open the doors for further improvements.
- Simple cmd
```
sub x 6.85 ops/sec ±1.95% (36 runs sampled)
execa x 13.13 ops/sec ±2.70% (63 runs sampled)
Fastest is execa
```
- for a full spawn
```js
const f = IPFSFactory.create()
f.spawn({
init: true,
start: false,
disposable: true
}, (err, _ipfsd) => {
console.log(err)
defer.resolve()
})
sub x 1.36 ops/sec ±29.12% (10 runs sampled)
execa x 2.82 ops/sec ±12.48% (19 runs sampled)
```
- full tests set went  2m 39s to 2m 14s `-25s`
=> feat: use execa instead of subcomandante

README.md, package-lock.json, package.json, src/factory-client.js, src/factory-daemon.js, src/index.js, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, test/api.spec.js, test/custom-api.spec.js
tests still not passing 
```bash
ipfsd.api for Daemons
go
1) test the ipfsd.api
(node:2935) UnhandledPromiseRejectionWarning: AssertionError: expected [Error: Command failed: /Users/hugomrdias/code/pl/js-ipfsd-ctl/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5101) failed: listen tcp4 127.0.0.1:5101: bind: address already in use
Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1
Swarm listening on /ip4/127.0.0.1/tcp/50306
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/50306
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
] to not exist
at df.spawn (/Users/hugomrdias/code/pl/js-ipfsd-ctl/test/api.spec.js:99:2 …
```
=> feat: change to ipfs-http-client

src/ipfsd-in-proc.js
We need to accept the `local` option for some tests:
https://github.com/ipfs/js-ipfs/blob/master/src/cli/commands/daemon.js#L28
=> chore: add local to opts args

src/ipfsd-in-proc.js
In the context of https://github.com/ipfs/js-ipfs/issues/1778 and https://github.com/ipfs/js-ipfs/pull/1850 , this is now needed for the tests.
BREAKING CHANGE: `--local` option has been renamed to `--offline`
=> fix: rename local flag to offline

src/ipfsd-daemon.js, test/add-retrieve.spec.js, test/api.spec.js, test/custom-api.spec.js, test/spawn-options.spec.js, test/start-stop.node.js
refs https://github.com/ipfs/js-ipfs-http-client/pull/942
=> feat: support passing profile init option

.aegir.js, .travis.yml, package.json
This PR adds a workaround to the windows secrets problem
```
jobs:
include:
- os: windows
filter_secrets: false
```
because we need to give bundlesize a token but we **should be very careful with this**. 
This disables the log secrets filtering making the token available if you echo the ENV var.
In this case is acceptable because the token only has access to commit_status in this repo.
needs:
[ipfs/aegir#feat/bundle-size](https://github.com/ipfs/aegir/pull/335)
=> feat: add bundlesize

src/ipfsd-in-proc.js
The latest version of js-ipfs takes `relay` at the first level of options, and not via the `config`. 
https://github.com/ipfs/js-ipfs/tree/v0.34.4#optionsrelay
In the next 0.35 release this will error, as the type checking is more strict.
=> fix: pass relay in via opts, not config

src/ipfsd-in-proc.js
In the context of [ipfs/js-ipfs#2298#pullrequestreview-280953619](https://github.com/ipfs/js-ipfs/pull/2298#pullrequestreview-280953619), we are moving to `enable-pubsub` instead.
=> chore: add enable-pubsub flag

package.json, src/endpoint/routes.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, test/npm-install.node.js, test/spawn-options.spec.js
In the context of [ipfs/js-ipfs#2298#pullrequestreview-280953619](https://github.com/ipfs/js-ipfs/pull/2298#pullrequestreview-280953619), we are moving to `enable-pubsub` instead.
`enabled` should be a property of pubsub, in order to allow the usage of other options.
This PR has a circular dependency issue with [ipfs/js-ipfs#2298](https://github.com/ipfs/js-ipfs/pull/2298)
=> fix: pubsub flag defaults

package.json
With [ipfs/js-ipfs#2298](https://github.com/ipfs/js-ipfs/pull/2298) merged, we can shift this to master until a new release is shipped for `js-ipfs`
=> chore: update ipfs dep

package.json, src/ipfsd-in-proc.js, test/spawn-options.spec.js
BREAKING CHANGE: pubsub flags for in-proc daemons will not set values anymore
As discussed, we will remove the pubsub flags from the js daemon and will use the config as the way to disable it (will be enabled by default now!)
Ref:
- [ipfs/go-ipfs#6621](https://github.com/ipfs/go-ipfs/issues/6621)
- [ipfs/js-ipfs#2427](https://github.com/ipfs/js-ipfs/pull/2427)
=> chore: remove pubsub flags

src/ipfsd-in-proc.js
in-proc daemon didnt support all the js-ipfs options, this should be improved so we dont need to syncronize manually.
this is related to https://github.com/ipfs/interop/pull/86 circuit tests were failing because relay: true wasnt being passed to the constructor
=> fix: support more ipfs options

README.md
> This PR addresses problems raised in https://github.com/ipfs-shipyard/ipfs-webui/pull/1353#discussion_r360726012
This PR:
- improves  Usage docs
- added code example for `createController`
- improved example for `createFactory` to show the value of shared factory template
- fixed return type of  `createController` in docs
=> docs: improve usage examples

.aegir.js, src/config.js, test/create.spec.js
New libp2p is strict about providing addrs that you can listen on.
https://github.com/libp2p/js-libp2p/blob/83409deaa6773a550d38b77bd486faf8b8b97d29/src/transport-manager.js#L172-L176
=> fix: remove swarm addrs in browser

.aegir.js, package.json
Otherwise we get multiple versions of multiaddr in the dep tree.
Does not upgrade Hapi because it's dropped support for node 10.  I don't know if we want that decision to be dependency led.
=> chore: update deps

.travis.yml
Only build master and release branches, PRs are built by travis so you only get one of these on each PR (e.g. the `Travis CI - Branch` one will not get built):
=> chore: only build master and PRs

.travis.yml, README.md, package.json, src/factory.js, src/utils.js
Doing this reduced the size of `node_modules` in the js-IPFS module for me by about 300MB and should result in a faster CI run for js-IPFS since it doesn't need to install itself.
Does require the user to bring their own version, but they can also skip installing go-IPFS if, for example, they are only going to use js-IPFS.
=> feat: move ipfs to peer deps

README.md, src/factory.js, src/index.js, src/ipfsd-daemon.js
This PR re-adds a feature that was removed in 1.0.0 whereby daemons are force killed with a SIGKILL when they do not stop within a timeout.
It adds 2 new options to the `Daemon` class - `forceKill` (boolean - default `true`) and `forceKillTimeout` (number - default 10000).
resolves https://github.com/ipfs/js-ipfsd-ctl/issues/438
=> feat: force kill daemons after timeout

src/factory.js
With this change only when `type === go` the option can be an empty object.
=> fix: protect possible empty ipfsModule option

src/factory.js
Only use `findBin` if it's not been specified in options.
In js-ipfs we set `ipfsBin` to be `./src/cli/bin.js` and there is no `ipfs` module installed (we are the module).
Proc node does not use `ipfsBin`
=> fix: only find bin if not overridden

.aegir.js, .travis.yml, package.json, src/factory.js
If we configure which http api module to use, don't try to require `ipfs-http-client`, because that then means the containing project needs to specify a dependency on `ipfs-http-client` when the containing project might actually be `ipfs-http-client`...
=> fix: only require http api client if it has not been specified

.aegir.js, src/endpoint/routes.js, src/factory.js, src/index.js, src/ipfsd-client.js, test/browser.utils.js, test/controller.spec.js, test/create.spec.js, test/factory.spec.js, test/node.routes.js, test/node.utils.js
There are just too many options, too many variables and too many different calling contexts so let's get the user to be explicit about how they intend to use the module rather than try to second guess them.
Also, allow the user to specify opts/overrides to the ipfsd server's use of `createFactory`.
=> refactor: remove option normalisation

.aegir.js, examples/electron-asar/app.js, examples/electron-asar/package.json, examples/id/id.js, examples/remote-disposable/remote-disposable.js, package.json, src/index.js, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, src/utils.browser.js, src/utils.js, test/browser.utils.js, test/controller.spec.js, test/create.spec.js, test/factory.spec.js, test/node.routes.js, test/node.utils.js
Since we're not passing modules to `.spawn()` there's no danger of passing module refs over http, so we can remove the `.path` and `.ref` arguments when specifying which `ipfs-http-client` and `ipfs` modules to use, instead setting them up when you configure the daemon factory, either in-proc or as a server in an `.aegir` file.
Also removes the `findBin` command magic in favour of being explicit about which binary you want the factory to use.
If you need to support env vars like `IPFS_GO_EXEC`, do that when you set up the factory, for example:
```javascript
const factory = createFactory({
ipfsBin: process.env.IPFS_GO_EXEC || require('go-ipfs-dep').path()
})
```
Also fixes up the examples and upgrades the `ipfs` dep to run tests against the async/await refactor.
BREAKING CHANGES:
- `.path` …
=> refactor: remove path and ref from module args also findBin

examples/electron-asar/package.json, package.json, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, test/benchmark.js, test/controller.spec.js
`go-ipfs@0.5.0` doesn't support keys < 2048 so let the implementation decide what the default key size should be.
The value is overridable as before by setting `ipfsOptions.init.bits` in the node setup.
=> feat: remove default key size and upgrade go-ipfs-dep

package.json, src/utils.browser.js, test/browser.utils.js
If we try to shut a node down while a query is still in flight it errors out.  The change here is to retry deleting the databse when we detect that it's still open, 5x attempts, each waiting 1-5s before trying again.  If it's still open after that, bail.
=> fix: remove onBlocked hook from delete database

.aegir.js, CHANGELOG.md, README.md, examples/electron-asar/app.js, examples/electron-asar/package.json, examples/id/id.js, examples/remote-disposable/remote-disposable.js, package.json, test/controller.spec.js, test/create.spec.js, test/factory.spec.js, test/node.js
The `go-ipfs` module does exactly what `go-ipfs-dep` does except it's got a much better name.
The plan is to encourage people to use `go-ipfs` instead as there's no need for us to maintain both.
BREAKING CHANGE:
- Previously dependent projects should also depend on `go-ipfs-dep`, now they should depend on `go-ipfs` instead
=> feat: swap go-ipfs-dep for go-ipfs

package.json, src/ipfsd-daemon.js, test/factory.spec.js
The `--enable-sharding-experiment` CLI arg causes go-ipfs to explode, instead set it as part of the config file.
=> fix: allow enabling sharding

.aegir.js, package.json, test/benchmark.js, test/controller.spec.js
Removes `bits` option when initting go-ipfs repos as the move to ed25519 keys makes it throw when `bits` is passed.
=> feat: go-ipfs 0.7.0 compatibility

.travis.yml, package.json
If you are in the Electron Renderer process, native fetch is available but it's ignored because the renderer does not respect the browser field of package.json, so we end up with node-fetch that uses a browser polyfill of the node http api.
Instead use native fetch if it's available or node fetch if not.
=> fix: use native fetch if available

package.json, src/ipfsd-daemon.js, test/controller.spec.js
Fixes two problems:
1. If we use `ipfs-daemon` to connect to a running node, there's no `this.subprocess` only `this.api` so don't reference that property in the `this.stop()` method.
2. There's a delay between stopping the process and the process actually stopping - in CI we don't wait for this and start new tests which start new processes which can overwhelm small weak build machines so wait for the subprocess to stop before returning from `this.stop()`
Changes behaviour:
1. Let the exiting of `this.subprocess` set `this.started = false` instead of when we stop the process
2. If a node is marked `disposable`, we don't really care about it exiting cleanly as we're going to delete it's repo shortly afterwards so just `SIGKILL` it immediately.
=> fix: kill disposable nodes on stop and simplify started status

src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, test/create.spec.js
ipfs/js-ipfs#3550 switches away from default exports for `ipfs-http-client`
and `ipfs-client` to enable an easier transition to es6 modules.
All `ipfs` modules now export a `.create` factory function which returns
instances of the client module.
BREAKING CHANGE: expects `ipfs-http-client` and `ipfs-client` to export a `.create` function
=> chore: use `.create` function for http client and ipfs client

.aegir.js, .github/workflows/main.yml, package.json, scripts/node-globals.js, src/factory.js, src/utils.browser.js, test/factory.spec.js, test/node.routes.js, test/node.utils.js
We added ipfs, the http client etc as peer deps to signal to the user
that they should add the modules they depend on as deps of their project.
Starting with npm7 all peer deps get installed automatically which
defeats the purpose of our use of peer deps, so let's remove them.
=> chore: remove peer deps

package.json, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js
=> chore: update multiaddr

src/types.d.ts, test/controller.spec.js, test/create.spec.js
Add `.opts` arg to `Factory` interface as it's used by the `interface-ipfs-core` tests.
Also stop extending IPFS, just use the core api and if you need id/config details call the relevant API methods instead.
=> fix: add factory opts and use ipfs api

src/ipfsd-daemon.js, src/utils.js
`fs.rmdir` with the `recursive` option is deprecated in favour of `fs.rm`
with the `recursive` operation, so use that instead.
=> fix: silence deprecation warning for fs.rmdir

src/factory.js
Fixes #760; electron main process can be treated as node.js, so we don't need to use remote server.
=> fix: make sure to behave as node.js in electron main process

package.json, test/controller.spec.ts, test/factory.spec.ts
Now that isOnline will not throw when the node is offline, re-enable tests that use this API call.
=> chore: re-enable tests that use isOnline

src/kubo/index.ts, src/kubo/utils.ts, test/kubo/utils.node.ts
=> fix: enable pubsub

src/endpoint/routes.ts, src/endpoint/server.ts, src/index.ts, test/create.spec.ts, test/endpoint/routes.node.ts
Like `factory.clean`, `server.clean` shuts down any running Kubo nodes created by the server and removes references to them.
=> feat: add server.clean method

src/kubo/daemon.ts
Sometimes the daemon will be running but without listen addresses.
=> fix: stop daemon even if offline
