index.js
This fixed failures on my machine.
=> Shot in the dark

index.js
This should be a minor version bump
=> Make ipfsd.local return a node instance

index.js, package.json, test/test.js
use subcomandante instead of comandante to solve the zombie problem.
subcomandante currently busy waits... ideally need to _wait_ on a pid.
but dont know how to do that in node yet.
=> use subcomandante instead of comandante

.travis.yml
=> added travis support

index.js, package.json, test/test.js
=> Exposes a disposableApi's host and port.

.travis.yml, index.js, package.json
had tests failing because `initOps` was creating a mem leak and it was just a typo :) 
plus removed unused requires
=> fix mem leak which was caused by typo on var name

index.js, test/test.js
#24 
@Dignifiedquire @VictorBjelkholm could you review this?
=> add setConfig feature and test

.travis.yml, README.md, circle.yml, examples/id.js, examples/local.js, index.js, lib/node.js, package.json, test/test.js
- Node >= 4
- ES2015 refactor
- `$IPFS_EXEC` to configure the path to the ipfs executable
=> Cleanup, refactor and configurable executable

src/node.js, test/index.spec.js
https://github.com/ipfs/js-ipfsd-ctl/issues/152
=> fix: show whole config

README.md, src/ipfsd-daemon.js, test/start-stop.node.js
Use IPFS_GO_EXEC and IPFS_JS_EXEC to set the executable through the environment
=> add ability to use go and js env exec

src/ipfsd-daemon.js
=> fix: Daemon spawning throws error with the new multiaddr version

package.json
=> chore: upgrade ipfs version to v29

src/ipfsd-in-proc.js
We are going all-in with mfs and not having it behind a flag: https://github.com/ipfs/js-ipfs/pull/1360#issuecomment-393847985
=> chore: remove experimental mfs flag

src/ipfsd-daemon.js
I find myself making this change all the time to see logs from the daemon when writing interop tests.
With this change to see output from the daemon you can do:
```sh
$ DEBUG=ipfsd-ctl:daemon:* npm test
```
=> chore: log daemon stdout and stderr

package.json
License: MIT
Signed-off-by: Alan Shaw <alan@tableflip.io>
=> chore: update ipfs-api dependency

README.md, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js
init should return ipfsd instance in the callback but didn't
closes #289
=> fix: fix ipfsd.init return value

src/ipfsd-client.js, src/ipfsd-in-proc.js
=> fix: linting errors

src/ipfsd-in-proc.js
Add experimental flag for DHT to be used in tests.
Needed for [js-ipfs#856](https://github.com/ipfs/js-ipfs/pull/856)
=> feat: add dht experimental flag

package.json, src/ipfsd-client.js, src/ipfsd-daemon.js, test/api.spec.js, test/fixtures/talky.js
needs:
https://github.com/ipfs/js-ipfs-http-client/pull/974
=> fix: updates deps and http for name resolve dns

examples/electron-asar/app.js, examples/electron-asar/package.json
Adds configuration to server creation and updates deps
=> docs: update electron example

src/ipfsd-daemon.js, src/utils.js, test/node.utils.js
Adds support and tests for supplying `--algorithm` to `ipfs init` and `--migrate` to `ipfs daemon`
=> feat: support more cli args

src/ipfsd-in-proc.js
https://github.com/ipfs/js-ipfs/pull/3365 make `ipfs.init()` obsolete and these changes update implementation so that `ipfs.init()` is no longer used.
=> chore: remove dependency on ipfs.init()

package.json, src/factory.js, src/index.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, src/types.d.ts, test/controller.spec.js, test/factory.spec.js
More comprehensive types available.  Also turn factory into an interface.
=> fix: types again

.github/workflows/main.yml, examples/electron-asar/app.js, package.json, src/endpoint/routes.js, src/ipfsd-client.js, src/ipfsd-daemon.js, src/ipfsd-in-proc.js, src/types.d.ts, src/utils.js, test/factory.spec.js
=> feat: expose apiAddr property

README.md, package.json, src/types.ts
Update all deps to latest versions
BREAKING CHANGE: pulls in new peer-id interface
=> feat!: update deps

.github/dependabot.yml, README.md, package.json
Update config for better changelog generation
=> chore: update project config

src/factory.ts, src/index.ts, src/kubo/daemon.ts, test/create.spec.ts
Allow passing endpoint to client
=> fix: use configured endpoint instead of default

src/factory.ts, src/index.ts, src/kubo/daemon.ts
=> fix: more helpful error messages

src/index.ts, src/kubo/client.ts, src/kubo/daemon.ts, src/kubo/index.ts
When the api fails to stop the process, kill it forcefully
=> fix: kill subprocess after timeout
